# @file .github/workflows/build.yml
# @brief GitHub Action: сборка APK и зависимостей C++ (boost + crown)

name: Build APK and Generate Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # JDK и Gradle
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.10
    - name: Generate Gradle Wrapper
      run: gradle wrapper --gradle-version 8.10
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Release APK
      run: ./gradlew clean assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ytgui
        path: app/build/outputs/apk/**/**/*.apk

